name: Build SentinelCore

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build AppImage
        run: |
          pyinstaller --noconfirm --onefile ui/qt_main.py
          mkdir -p AppDir/usr/bin
          cp dist/qt_main AppDir/usr/bin/
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage AppDir

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SentinelCore-Linux
          path: ./SentinelCore*.AppImage
